In [ ]:
####
# Important Note: D-Wave does not allow free LEAP access tokens anymore.  
# Please reach out to D-Wave or sign up using https://www.dwavesys.com/quantum-launchpad/
###

In [2]:
# Copyright 2020 Alex Khan
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Things to do:
 - Please name this file <demo_name>.py
 - Fill in [yyyy] and [name of copyright owner] in the copyright (top line)
 - Add demo code below
 - Format code so that it conforms with PEP 8
"""

import numpy as np
from numpy.random import rand

from dwave.system.samplers import DWaveSampler
from dwave.system.composites import EmbeddingComposite
from minorminer import find_embedding
import networkx as nx
import dwave.inspector

# Random matrix
dim=5
Q =  2*rand(dim,dim) - 1
Q = (Q+Q.T)/2
for k in range(dim):
    Q[k,k] = np.abs(Q[k,k])

#Problem -> Solution
# Creating a formula that is in this qubit adder formulation 
# QUBO - Quadratic Unconstrained Binary Optimization
# Balance your QUBO

# Example
#[[ -0.11209597 -0.005184097]
# [             0.05494179]]

# Solve your problem here
# Create a matrix that represents the problem
# Submit the matrix to DWave
print(Q)
# convert matrix into a QUBO with linear=biases and quadratic=couplings terms
linear={('a'+str(k), 'a'+str(k)):Q[k][k] for k in range(dim)}

quadratic={('a'+str(i+1), 'a'+str(j)):Q[i+1][j] for i in range(dim-1) for j in range(dim-1) if j<i+1}

QDwave = dict(linear)
QDwave.update(quadratic)

print(QDwave)

chainstrength = 10
numruns = 10

#clique = nx.complete_graph(7).edges()
#target_graph = nx.random_regular_graph(d=4, n=30).edges()
#embedding = find_embedding(clique, target_graph)
#print(embedding)

sampler = EmbeddingComposite(DWaveSampler())


response = sampler.sample_qubo(QDwave, chain_strength=chainstrength, num_reads=numruns)
print(response)
#dwave.inspector.show(QDwave,response)


[[ 0.77696404 -0.43936446  0.28997879  0.36922696 -0.08951499]
 [-0.43936446  0.70594143  0.71667432 -0.7494119   0.01707446]
 [ 0.28997879  0.71667432  0.69197452  0.91856414 -0.60743822]
 [ 0.36922696 -0.7494119   0.91856414  0.66400274  0.51092509]
 [-0.08951499  0.01707446 -0.60743822  0.51092509  0.85715102]]
{('a0', 'a0'): np.float64(0.7769640428944384), ('a1', 'a1'): np.float64(0.7059414337753473), ('a2', 'a2'): np.float64(0.6919745198340588), ('a3', 'a3'): np.float64(0.6640027404615565), ('a4', 'a4'): np.float64(0.8571510243111613), ('a1', 'a0'): np.float64(-0.43936445895202325), ('a2', 'a0'): np.float64(0.28997879192723064), ('a2', 'a1'): np.float64(0.7166743179897977), ('a3', 'a0'): np.float64(0.3692269571203308), ('a3', 'a1'): np.float64(-0.7494118958130941), ('a3', 'a2'): np.float64(0.9185641404491922), ('a4', 'a0'): np.float64(-0.08951499477272962), ('a4', 'a1'): np.float64(0.017074464707011017), ('a4', 'a2'): np.float64(-0.6074382218910365), ('a4', 'a3'): np.float64(0.510